# Error function in Python
raise Exception('please try again')
