# Issue with Exception in Python
initialize_logging(__file__)
