# Python 3.x socket.error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions
s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
