# Python 3.2 SQLite 3 Error with connect function
&gt;&gt;&gt; import sqlite3
&gt;&gt;&gt; conn = sqlite3.connect('example.db')
