# How can I resolve 'django_content_type already exists'?
python manage.py migrate --fake-initial
